apiVersion: v1
kind: Service
metadata:
  name: projekt2-mongodb
  labels:
    app: projekt2-mongo
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: projekt2-mongo
  ports:
    - port: 27017
      targetPort: 27017


# Dieser Service stellt die Verbindung zu den MongoDB-Pods im Cluster her.
# Durch 'clusterIP: None' handelt es sich um einen sogenannten Headless-Service,
# der benötigt wird, damit StatefulSets wie MongoDB mit festen DNS-Namen arbeiten können.
# 'publishNotReadyAddresses: true' sorgt dafür, dass die Pods auch schon erreichbar sind,
# bevor sie als bereit gelten. Das ist wichtig für die Replika-Initialisierung.
